In [48]:
import pandas as pd
import sqlite3

In [49]:
conn = sqlite3.connect("chatbot.db")

In [50]:
pd.read_sql("SELECT * FROM feedback", conn)

   id                            message_id feedback           api_key
0   1  c31df641-dbd5-45d7-a7e3-5afe96409604     like  test-api-key-456
1   2  c8577a0d-208e-4f53-ace9-565be177ba82     like  test-api-key-456
2   3  dcb4e2de-5cc9-42c0-b7c4-05f6b42002bf     like  test-api-key-456
3   4  d6fb2199-6596-4286-9716-d8ab93e7fafd     like  test-api-key-456
4   5  d8b045ea-01bf-42f7-a4d4-c860d3345e3b     like  test-api-key-456
5   6  c6dc12bb-66fb-4c17-b6af-2a727c69abba     like  test-api-key-456
6   7  d72868b9-0f95-49d5-9ad0-2f5046cc1e40     like  test-api-key-456

In [51]:
pd.read_sql("SELECT * FROM messages", conn)

,id,api_key,role,text,message_id
0,1,test-api-key-456,assistant,Для внесения данных по личному автомобилю обра...,c31df641-dbd5-45d7-a7e3-5afe96409604
1,2,test-api-key-456,user,как зарегестрирова машину,ba0d4ee2-6323-40c1-9109-fc9987240ed4
2,3,test-api-key-456,assistant,Заработная плата в нашей компании выплачиваетс...,c8577a0d-208e-4f53-ace9-565be177ba82
3,4,test-api-key-456,user,когда зарплата?,31d02cbc-ea11-485d-9676-b7373340623e
4,5,test-api-key-456,assistant,"Не уверен, что понял вас, попробуйте добавить ...",dcb4e2de-5cc9-42c0-b7c4-05f6b42002bf
5,6,test-api-key-456,user,пиво,8327b7dc-f3c1-4521-aae2-955004ff8953
6,7,test-api-key-456,assistant,"Не уверен, что понял вас, попробуйте добавить ...",d6fb2199-6596-4286-9716-d8ab93e7fafd
7,8,test-api-key-456,user,опаплодаволавлоа,fb2c3e19-ff05-4e72-9e32-d40ec7177a70
8,9,test-api-key-456,assistant,"Не уверен, что понял вас, попробуйте добавить ...",d8b045ea-01bf-42f7-a4d4-c860d3345e3b
9,10,test-api-key-456,user,пися попа,a82f8a7d-5ee4-4588-a6bc-3d0042a66f1d
10,11,test-api-key-456,assistant,"Создать заявку на отпуск можно в разделе ""Серв...",c6dc12bb-66fb-4c17-b6af-2a727c69abba
11,12,test-api-key-456,user,как оформить отпуск,14917853-4501-4e8e-bc01-25e2b383957e
12,13,test-api-key-456,assistant,"Обратитесь к HRBP для создания заявки ""Админис...",d72868b9-0f95-49d5-9ad0-2f5046cc1e40
13,14,test-api-key-456,user,я хочу уйти в декрет,494176c3-9ee3-4b7a-b9cc-4a3d585d9eca