In [34]:
import pandas as pd
import sqlite3

In [35]:
conn = sqlite3.connect("chatbot.db")

In [36]:
pd.read_sql("SELECT * FROM feedback", conn)

   id                            message_id feedback           api_key
0   1  9eca9957-6573-4571-b70c-927659fefdfa     like  test-api-key-123
1   2  3c616372-351a-4ee4-b1d9-a9a6a29f996c  dislike  test-api-key-123
2   3  40230295-b638-42ef-a51d-f0ab22d12729     like  test-api-key-123
3   4  54d09ac2-a156-4e93-a161-acced5d8f9e7     like  test-api-key-123

In [37]:
pd.read_sql("SELECT * FROM messages", conn)

,id,api_key,role,text,message_id
0,1,test-api-key-123,user,апорапорпаорпа,b5a05658-c1d2-4210-aa7d-e92eca434fa2
1,2,test-api-key-123,assistant,Получено: апорапорпаорпа. Это заглушка ответа ...,9eca9957-6573-4571-b70c-927659fefdfa
2,3,test-api-key-123,user,а,719103d3-d7ff-404f-8d1c-3e0d6bd23af1
3,4,test-api-key-123,assistant,Получено: а. Это заглушка ответа от AI!,3c616372-351a-4ee4-b1d9-a9a6a29f996c
4,5,test-api-key-123,user,а,442bb402-616b-46b2-b4ff-43eab5f301cf
5,6,test-api-key-123,assistant,Получено: а. Это заглушка ответа от AI!,40230295-b638-42ef-a51d-f0ab22d12729
6,7,test-api-key-123,user,ва,f4c11a65-7bb4-44bb-9837-b2574a24c41d
7,8,test-api-key-123,assistant,Получено: ва. Это заглушка ответа от AI!,54d09ac2-a156-4e93-a161-acced5d8f9e7