In [62]:
import pandas as pd
import sqlite3

In [63]:
conn = sqlite3.connect("chatbot.db")

In [64]:
pd.read_sql("SELECT * FROM feedback", conn)

   id                            message_id feedback           api_key
0   3  ebaf8ff9-e86f-44b4-9add-48e62e6aff51  dislike  test-api-key-123
1   4  e4a6e242-29b2-4160-bbb3-cd2c9c0ce3dc     like  test-api-key-123
2   5  d537abe2-8fff-44f9-a604-b17221a3051d     like  test-api-key-123

In [65]:
pd.read_sql("SELECT * FROM messages", conn)

,id,api_key,role,text,message_id
0,13,test-api-key-123,user,ававва,47bf730f-c0f5-4a2b-9f81-cba338c2365d
1,14,test-api-key-123,assistant,Получено: ававва. Это заглушка ответа от AI!,ebaf8ff9-e86f-44b4-9add-48e62e6aff51
2,15,test-api-key-123,user,ав,9fea6b63-b2b5-4ad7-b653-79624c950f67
3,16,test-api-key-123,assistant,Получено: ав. Это заглушка ответа от AI!,e4a6e242-29b2-4160-bbb3-cd2c9c0ce3dc
4,17,test-api-key-123,user,ав,38c3429c-f2f4-444d-806e-dd2150f129be
5,18,test-api-key-123,assistant,Получено: ав. Это заглушка ответа от AI!,d537abe2-8fff-44f9-a604-b17221a3051d